import client from "./index.js"
export const TICK_DURATION_MS = 100
export async function acceptCargo(...args) { return client.emitOp({ functionName: "acceptCargo", args })}
export async function activateModule(...args) { return client.emitOp({ functionName: "activateModule", args })}
export async function activateModuleById(...args) { return client.emitOp({ functionName: "activateModuleById", args })}
export async function activateShield(...args) { return client.emitOp({ functionName: "activateShield", args })}
export async function alignToEntity(...args) { return client.emitOp({ functionName: "alignToEntity", args })}
export async function alignToVector(...args) { return client.emitOp({ functionName: "alignToVector", args })}
export async function attachModule(...args) { return client.emitOp({ functionName: "attachModule", args })}
export async function broadcast(...args) { return client.emitOp({ functionName: "broadcast", args })}
export async function clearModuleTarget(...args) { return client.emitOp({ functionName: "clearModuleTarget", args })}
export async function clearModuleTargetCoordinates(...args) { return client.emitOp({ functionName: "clearModuleTargetCoordinates", args })}
export async function clearSlot(...args) { return client.emitOp({ functionName: "clearSlot", args })}
export async function deactivateModule(...args) { return client.emitOp({ functionName: "deactivateModule", args })}
export async function deactivateModuleById(...args) { return client.emitOp({ functionName: "deactivateModuleById", args })}
export async function deactivateShield(...args) { return client.emitOp({ functionName: "deactivateShield", args })}
export async function detachModuleById(...args) { return client.emitOp({ functionName: "detachModuleById", args })}
export async function detachModuleBySlot(...args) { return client.emitOp({ functionName: "detachModuleBySlot", args })}
export async function disengageWarp(...args) { return client.emitOp({ functionName: "disengageWarp", args })}
export async function engageWarp(...args) { return client.emitOp({ functionName: "engageWarp", args })}
export async function fireWeapon(...args) { return client.emitOp({ functionName: "fireWeapon", args })}
export async function fireWeaponAtCoordinates(...args) { return client.emitOp({ functionName: "fireWeaponAtCoordinates", args })}
export async function getAllCargo(...args) { return client.emitOp({ functionName: "getAllCargo", args })}
export async function getAllModules(...args) { return client.emitOp({ functionName: "getAllModules", args })}
export async function getAllSchematics(...args) { return client.emitOp({ functionName: "getAllSchematics", args })}
export async function getLocalMap(...args) { return client.emitOp({ functionName: "getLocalMap", args })}
export async function getModuleStatus(...args) { return client.emitOp({ functionName: "getModuleStatus", args })}
export async function getPosition(...args) { return client.emitOp({ functionName: "getPosition", args })}
export async function getRotation(...args) { return client.emitOp({ functionName: "getRotation", args })}
export async function getShieldStatus(...args) { return client.emitOp({ functionName: "getShieldStatus", args })}
export async function getStatus(...args) { return client.emitOp({ functionName: "getStatus", args })}
export async function getTick(...args) { return client.emitOp({ functionName: "getTick", args })}
export async function getVelocity(...args) { return client.emitOp({ functionName: "getVelocity", args })}
export async function getWarpStatus(...args) { return client.emitOp({ functionName: "getWarpStatus", args })}
export async function getWarpTarget(...args) { return client.emitOp({ functionName: "getWarpTarget", args })}
export async function jettisonCargo(...args) { return client.emitOp({ functionName: "jettisonCargo", args })}
export async function manufactureItem(...args) { return client.emitOp({ functionName: "manufactureItem", args })}
export async function requestDocking(...args) { return client.emitOp({ functionName: "requestDocking", args })}
export async function researchMaterial(...args) { return client.emitOp({ functionName: "researchMaterial", args })}
export async function routePower(...args) { return client.emitOp({ functionName: "routePower", args })}
export async function scan(...args) { return client.emitOp({ functionName: "scan", args })}
export async function setBackwardThrust(...args) { return client.emitOp({ functionName: "setBackwardThrust", args })}
export async function setCourse(...args) { return client.emitOp({ functionName: "setCourse", args })}
export async function setForwardThrust(...args) { return client.emitOp({ functionName: "setForwardThrust", args })}
export async function setLateralThrust(...args) { return client.emitOp({ functionName: "setLateralThrust", args })}
export async function setModuleTarget(...args) { return client.emitOp({ functionName: "setModuleTarget", args })}
export async function setModuleTargetCoordinates(...args) { return client.emitOp({ functionName: "setModuleTargetCoordinates", args })}
export async function setRotationTarget(...args) { return client.emitOp({ functionName: "setRotationTarget", args })}
export async function setSlot(...args) { return client.emitOp({ functionName: "setSlot", args })}
export async function setTurnRate(...args) { return client.emitOp({ functionName: "setTurnRate", args })}
export async function setWarpTarget(...args) { return client.emitOp({ functionName: "setWarpTarget", args })}
export async function synthesizeMaterial(...args) { return client.emitOp({ functionName: "synthesizeMaterial", args })}